version: '3.8'

services:
  db:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: files
      MYSQL_PASSWORD: files
      MYSQL_DATABASE: files
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - backend
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - db # This service depends on mysql. Start that first.
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      MYSQL_ROOT_PASSWORD: files
      MYSQL_USER: files
      MYSQL_PASSWORD: files
      MYSQL_DATABASE: files
    volumes:
      - .:/app
    networks:
      - backend
  web:
    build:
      context: web
      target: builder
    ports:
      - 4200:4200
    volumes:
      - ./web:/project
      - /project/node_modules
networks:
  backend:
